# Generated by Django 3.2 on 2021-04-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('zip', models.CharField(max_length=10)),
            ],
        ),
    ]
