# Generated by Django 4.1.7 on 2023-04-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='zip',
        ),
    ]
